version: '3'

services:
  # my-service:
  #   build: ${MY_SERVICE_HOME}/spring-boot-demo-app
  #   container_name: my-service
  #   networks: ['my-service-network']
  #   tty: true
  #   ports:
  #     - "8080:8080"

  py-web:
    build: .
    ports:
      - "5000:5000"

  redis:
    image: "redis:alpine"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks: ['my-service-network']
    ports:
      - "8081:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
    # entrypoint:
    #   - /bin/prometheus
    #   - --config.file=/etc/prometheus/prometheus.yml
    # command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks: ['my-service-network']
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "8082:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false

networkds: {my-service-network: {}}
