{
 "title": "Spring Boot Statistics",
 "description": "Dashboard for Spring Boot2 Statistics.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(http_server_requests_seconds_count{application=\"$application\"}, instance)"
   },
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   { "name": "uri", "label": "URI" }
  ]
 },
 "panels": [
  { "title": "Backend calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(backend_calls_seconds_count{application=\"$application\", exception=\"none\"}[5m])",
     "legendFormat": "{{exception}}"
    },
    {
     "expr": "irate(backend_calls_seconds_count{application=\"$application\", exception!=\"none\"}[5m])",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Percentage of errors last 15m",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(backend_calls_seconds_count{application=\"my-service\", exception!=\"none\"}[15m])) / sum(increase(backend_calls_seconds_count{application=\"my-service\"}[15m])) * 100"
    }
   ]
  },
  {
   "title": "Number errors last 15m",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(backend_calls_seconds_count{application=\"my-service\", exception!=\"none\"}[15m]))"
    }
   ]
  },
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{application=\"$application\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "HTTP Requests Error Rate last 30 min",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(tomcat_global_request_seconds_count{application=\"$application\", status!=\"200\"}[30m])) / sum(increase(tomcat_global_request_seconds_count{application=\"$application\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "Failed in the last 30 min",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "format": "locale",
   "valueName": "range",
   "targets": [
    {
     "expr": "sum(increase(tomcat_global_request_seconds_count{application=\"$application\", status!=\"200\"}[30m]))"
    }
   ]
  },
  {
   "title": "Request Count / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(tomcat_global_request_seconds_count{application=\"$application\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(tomcat_global_request_seconds_sum{application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(tomcat_global_request_seconds_count{application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time (percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri!~\".*actuator.*\"}[15s])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri!~\".*actuator.*\"}[15s])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri!~\".*actuator.*\"}[15s])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri!~\".*actuator.*\"}[15s])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Top 10 Most Used AI endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(tomcat_global_request_seconds_count{application=\"$application\", instance=~\"$instance\", uri!=\"*.actuator*\"}[1m])))"
    }
   ]
  },
  {
   "title": "Top 5 slowest API endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by(uri, method) (rate(tomcat_global_request_max_seconds{application=\"$application\", instance=~\"$instance\", uri!=\"*.actuator*\"}[1m])))"
    }
   ]
  },
  { "title": "Tomcat Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Total Error Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 44 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tomcat_global_error_total{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{application=\"$application\"}",
     "legendFormat": "active sessions"
    }
   ]
  },
  {
   "title": "Sent & Recieved Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(tomcat_global_sent_bytes_total{application=\"$application\"}[5m])",
     "legendFormat": "Sent Bytes"
    },
    {
     "expr": "irate(tomcat_global_received_bytes_total{application=\"$application\"}[5m])",
     "legendFormat": "Recieved Bytes"
    }
   ]
  },
  {
   "title": "Thread Config Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 48 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tomcat_threads_config_max_threads{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{application=\"$application\"}",
     "legendFormat": "Current thread"
    },
    {
     "expr": "tomcat_threads_busy_threads{application=\"$application\"}",
     "legendFormat": "Current thread busy"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\"}[10m])",
     "legendFormat": "{{level}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{application=\"$application\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "repeat": "memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{application=\"$application\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "repeat": "memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{application=\"$application\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{application=\"$application\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{application=\"$application\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{application=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{application=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{application=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  }
 ]
}